import { Pair } from './currencypair.model'
export interface OrderPlaced {
  /** Unique identifier of the order (generated by the server) */
  id?: string;

  /** Identifier or reference to the user who placed the order */
  userId?: string;

  /** Trading pair (e.g., 'BTC/USD', 'ETH/USDT') */
  pair: Pair;

  /** Order side: BUY or SELL */
  side: 'BUY' | 'SELL';

  /** Order type: LIMIT, MARKET, STOP_LIMIT, etc. */
  type: 'LIMIT' | 'MARKET' | 'STOP_LIMIT' | 'STOP_MARKET';

  /** Limit price for LIMIT orders (in quote currency) */
  price: number;

  /** Total order volume in base currency */
  volumeTotal: number;

  /** Volume already executed/filled */
  volumeFilled: number;

  /** Current status of the order */
  status: 'ACTIVE' | 'FILLED' | 'CANCELLED' | 'PARTIALLY_FILLED' | 'REJECTED' | 'EXPIRED';

  /** Timestamp when the order was created (ISO 8601) */
  createdAt: string; // or Date if you convert it

  /** Timestamp when the order was fully filled, cancelled, or expired */
  closedAt: string | null;

  /** Remaining volume to be filled */
  volumeRemaining: number;

  /** Amount reserved (locked) in the quote currency for this order */
  reservedAmount: number;

  /** Currency in which the amount is reserved (usually quote currency) */
  reservedCurrency: string;

  /** Reason if the order was rejected (if applicable) */
  rejectionReason: string | null;

  /** Whether the order has been completely filled */
  fullyFilled: boolean;

  /** Internal order ID from the exchange (often numeric) */
  orderId: number;

  // Optional: useful derived/computed fields (can be added later)
  // totalValue?: number; // price * volumeTotal
  // filledPercentage?: number;
}
